on: workflow_dispatch
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.USE_VARIABLES == 'true' }}
    runs-on: ${{ vars.RUNNER }}
    environment: development
    steps:
      - name: Use variables
        run: echo "test"
        # run: |
        #   echo "repository variable: ${{ vars.REPOSITORY_VAR }}"
        #   echo "organization variable(no value): ${{ vars.ORGANIZATION_VAR }}"
        #   echo "overridden variable: ${{ vars.OVERRIDE_VAR }}"
        #   echo "variable from shell environment: $env_var"

      - name: ${{ vars.HELLO_WORLD_STEP }}
        if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ vars.GREET_NAME }}
