name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -l
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
  clone-another-repo:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -l
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/checkout@v3
        with:
          repository: toyozaki/nextjs-template
          path: another
      - run: pwd
      - run: ls -l
      - run: ls -l {{ github.workspace }}/main
      - run: ls -l {{ github.workspace }}/another
      
