name: study-github-action-expressions
run-name: ${{ github.actor }} is studying github-action expressions
on: [push]
jobs:
  sample-expressions:
    runs-on: ubuntu-latest
    steps:
      - name: literals
        run: |
          echo $myNull
          echo $myBoolean
          echo $myInt
          echo $myFloat
          echo $myHex
          echo $myExponential
          echo $myString
          echo $myStringInBraces
          echo $myErrStringInBraces
        env:
          myNull: ${{ null }}
          myBoolean: ${{ true }}
          myInt: ${{ 7 }}
          myFloat: ${{ 7.7 }}
          myHex: ${{ 0x77 }}
          myExponential: ${{ -2.99e-2 }}
          myString: This is a string
          myStringInBraces: ${{ 'It''s open source!' }}
          # myErrStringInBraces: ${{ "It's open source!" }}

      - name: operators
        run: |
          echo $expr1
          echo $expr2
          echo $expr3
          echo $expr4
          echo $expr5
          echo $expr6
          echo $expr7
          echo $expr8
          echo $expr9
        env:
          expr1: ${{ !false }}
          expr2: ${{ 2 > 1 }}
          expr3: ${{ 1 < 2 }}
          expr4: ${{ 1 <= 1 }}
          expr5: ${{ 2 >= 2 }}
          expr6: ${{ 'a' == 'a' }}
          expr7: ${{ 'a' != 'b' }}
          expr8: ${{ true && true }}
          expr9: ${{ true || false }}

      - name: loose equality comparisons
        run: |
          echo $expr1
          echo $expr2
          echo $expr3
          echo $expr4
          echo $expr5
          echo $expr6
          echo $expr7
          echo $expr8
          echo $expr9
          echo $expr10
        env:
          expr1: ${{ null == 0}}
          expr2: ${{ true == 1 }}
          expr3: ${{ false == 0 }}
          expr4: ${{ '' == 0 }}
          expr5: ${{ toJSON('[]') != NaN }}
          expr6: ${{ toJSON('{}') != NaN }}
          expr7: ${{ NaN != NaN }}
          expr8: ${{ 'a' == 'A' }}
          expr9: ${{ toJSON('[1]') == toJSON('[1]') }}
          expr10: ${{ toJSON('{"a": 1}') == toJSON('{"a": 1}') }}
