name: sample-workflow-caller
run-name: Call a reusable workflow
on: workflow_dispatch

jobs:
  call-workflow-passing-data:
    uses: toyozaki/my-reusable-workflows/.github/workflows/sample-reusable-workflow.yml@main
    with:
      your-name: potita
    secrets:
      your-age: '1000'
      
  job1:
    uses: toyozaki/my-reusable-workflows/.github/workflows/output-sample.yml@main
    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo ${{ needs.job1.outputs.firstword}} ${{ needs.job1.outputs.secondword }}
    
    
