name: study-github-action-expressions
run-name: {{ github.actor }} is studying github-action expressions
on: [push]
jobs:
  sample-expressions:
    run-on: ubuntu-latest
    steps:
      - name: literals
        run: |
          echo $myNull
          echo $myBoolean
          echo $myInt
          echo $myFloat
          echo $myHex
          echo $myExponential
          echo $myString
          echo $myStringInBraces
          # echo $myErrStringInBraces
        env:
          myNull: {{ null }}
          myBoolean: {{ true }}
          myInt: {{ 7 }}
          myFloat: {{ 7.7 }}
          myHex: {{ 0x77 }}
          myExponential: { -2.99e-2 }}
          myString: This is a string
          myStringInBraces: ${{ 'It's open source!' }}
          # myErrStringInBraces: ${{ "It's open source!" }}
