name: Test status check functions
on: push

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: This step will be executed
        run: echo "This step will be executed"
        
      - name: Failing step
        id: demo
        run: exit 1
        
      - name: The prev job has failed
        if: ${{ failure() && steps.demo.conclusion == 'failure' }}
        run: echo "The prev job has failed"
        
      - name: This step won't be executed
        if: ${{ success() }}
        run: echo "This step won't be executed"
        
      - name: This step will always be executed
        if: ${{ always() }}
        run: echo "This step will always be executed"

  test-2:
    runs-on: ubuntu-latest
    steps:
      - name: Any job has failed
        if: ${{ failure() }}
        run: echo "Any job has failed"
        
