name: upload-artifact
on: [push]
jobs:
  put-output-log:
    name: Save output
    steps:
      - name: Create output.log
        shell: bash
        run: |
          expr 1 + 1 > output.log
      
      - name: Upload output.log
        uses: actions/upload-artict@v3
        with:
          name: output-log-file
          path: output.log
  
  get-output-log:
    name: Get output from artifacats
    steps:
      - name: Download output.log
        uses: actions/download-artifacts@v3
        with:
          name: output-log-file
      
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -l
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
  clone-another-repo:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -l
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/checkout@v3
        with:
          repository: toyozaki/nextjs-template
          path: another
      - run: pwd
      - run: ls -l
      - run: ls -l ${{ github.workspace }}/main
      - run: ls -l ${{ github.workspace }}/another
      - run: |
          cd ${{ github.workspace }}/main
          pwd
          git log --oneline -n 10
